### ISSUE TITLE
Javascript .map file?

### ISSUE THREAD

**Issue by waynew** [kevalbhatt/timezone-picker#15]
Hi,

I've tried to generate a map file with this:

    uglifyjs timezone-picker.js  -o timezone-picker-1.0.2.min.js --source-map filename=timezone-picker-1.0.2.min.js.map -m 

But that ended out generating code that had different names than the released minified code. Can you either generate the map, or provide the commands that you used for generating the minified code?

**Comment by kevalbhatt** [comment]
@waynew I am going to release one new version 1.1.0 which will move this plugin to the es6 version with webpack this will solve your problem.

Mostly I will release this version tomorrow i.e 24-Jun-2018 Sunday (IST)

**Comment by waynew** [comment]
As an aside, we decided to go ahead and add our own packed version of this library because it has some surprising interactions with a LinkedIn tracker that adds a `unique` function to the Array prototype. It causes the `for <thing> in array` pattern to fail because it ends out enumerating over the property.

Great job, LinkedIn 😡 

Anyway, we added our own fixer that defines `Array.unique` to the value of `Array.unique` but we set it to be non-enumerable, and call that fixer at the beginning of each function call that does `for thing in stuff`. But it also means that we ended out having to release our own version of this library 🤷‍♂️ So we're building with the aforementioned command (though I think we added `--comment` to keep the license). But releasing with webpack is 👌

**Comment by kevalbhatt** [comment]
@waynew I have done **npm premajor** release with es6 and webpack support please check.

Right now dist folder has minified js but source-map is not included because it is production build file.

If you want to debug the project use following script

```js
npm run dev
```
