### ISSUE TITLE
Incorrect offset for "Asia/Kathmandu" timezone

### ISSUE THREAD

**Issue by seuck** [kevalbhatt/timezone-picker#17]
Asia/Kathmandu timezone si +05:45

So offset is 5.75, but data wrongly is set to 5.8.

**Comment by kevalbhatt** [comment]
@seuck https://timezonedb.com/time-zones/Asia/Kathmandu please see this.

**Comment by kevalbhatt** [comment]
@seuck if you found any link with the valid timezone detail please share with me, I would update the offset.

or you create the PR request
