### ISSUE TITLE
setValue and getValue undefined

### ISSUE THREAD

**Issue by oleglyakhovetskyi** [kevalbhatt/timezone-picker#5]
I just add one line in your example page

`    $('#map').data('timezonePicke').setValue('Asia/Kolkata')`

And function setValue undefined

**Comment by kevalbhatt** [comment]
@oleglyakhovetskyi It was my bad 

Please check the updated documentation.

> Use .data('timezonePicker') not .data('timezonePicke')

Please let me know if you are still facing the issue
